# config/database.yml
version: '2'
services:
  db:
    image: mysql:5.7.13
    ports:
      - "6603:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  app:
    build: .
    # command: bundle exec puma -C config/puma.rb
    # command: bundle exec unicorn -c config/unicorn.rb
    command: bundle exec unicorn -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./shared/sockets:/myapp/shared/sockets
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - 3003:80
    # crazy test
    volumes:
      - ./shared/sockets:/sockets
  search:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  data:

